export enum N8nEvent {
  GRIEF_FOLLOWUP_SCHEDULE = 'GRIEF_FOLLOWUP_SCHEDULE',
  STAFF_NOTIFY = 'STAFF_NOTIFY',
  DOC_GENERATE = 'DOC_GENERATE',
  INTAKE_NOTIFY = 'INTAKE_NOTIFY',
  REVIEW_REQUEST = 'REVIEW_REQUEST',
}
